# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: h:/VIVADO_PROJECTS/CPU/CPU.srcs/sources_1/ip/clk_wiz_pll/clk_wiz_pll.xci
# IP: The module: 'clk_wiz_pll' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/VIVADO_PROJECTS/CPU/CPU.gen/sources_1/ip/clk_wiz_pll/clk_wiz_pll_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_pll'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: h:/VIVADO_PROJECTS/CPU/CPU.gen/sources_1/ip/clk_wiz_pll/clk_wiz_pll.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: h:/VIVADO_PROJECTS/CPU/CPU.gen/sources_1/ip/clk_wiz_pll/clk_wiz_pll_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: h:/VIVADO_PROJECTS/CPU/CPU.srcs/sources_1/ip/clk_wiz_pll/clk_wiz_pll.xci
# IP: The module: 'clk_wiz_pll' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/VIVADO_PROJECTS/CPU/CPU.gen/sources_1/ip/clk_wiz_pll/clk_wiz_pll_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: h:/VIVADO_PROJECTS/CPU/CPU.gen/sources_1/ip/clk_wiz_pll/clk_wiz_pll.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: h:/VIVADO_PROJECTS/CPU/CPU.gen/sources_1/ip/clk_wiz_pll/clk_wiz_pll_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
