@echo off
REM ****************************************************************************
REM Vivado (TM) v2023.2 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Mon Mar 17 23:04:40 -0700 2025
REM SW Build 4029153 on Fri Oct 13 20:14:34 MDT 2023
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
REM elaborate design
echo "xelab --incr --debug typical --relax --mt 2 -L xil_defaultlib -L axi_bram_ctrl_v4_1_9 -L blk_mem_gen_v8_4_7 -L lib_pkg_v1_0_3 -L lib_srl_fifo_v1_0_3 -L emc_common_v3_0_6 -L axi_emc_v3_0_29 -L axi_lite_ipif_v3_0_4 -L lib_cdc_v1_0_2 -L axi_uartlite_v2_0_33 -L dist_mem_gen_v8_0_14 -L fifo_generator_v13_2_9 -L lib_fifo_v1_0_18 -L interrupt_control_v3_1_5 -L axi_quad_spi_v3_2_28 -L uvm -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot cpu_core_tb_behav xil_defaultlib.cpu_core_tb xil_defaultlib.glbl -log elaborate.log"
call xelab  --incr --debug typical --relax --mt 2 -L xil_defaultlib -L axi_bram_ctrl_v4_1_9 -L blk_mem_gen_v8_4_7 -L lib_pkg_v1_0_3 -L lib_srl_fifo_v1_0_3 -L emc_common_v3_0_6 -L axi_emc_v3_0_29 -L axi_lite_ipif_v3_0_4 -L lib_cdc_v1_0_2 -L axi_uartlite_v2_0_33 -L dist_mem_gen_v8_0_14 -L fifo_generator_v13_2_9 -L lib_fifo_v1_0_18 -L interrupt_control_v3_1_5 -L axi_quad_spi_v3_2_28 -L uvm -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot cpu_core_tb_behav xil_defaultlib.cpu_core_tb xil_defaultlib.glbl -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
